import { useState } from 'react';
import { DashboardChart } from '../../components/DashboardChart';
import { EmptyRow, formatMoney, formatNumber, ShopHeader, ShopState, total, type ShopRow, useShopChart, useShopSection } from './shared';

export function CostAnalysis() {
  const state=useShopSection('costs'); const {rows}=state; const [selected,setSelected]=useState<ShopRow|null>(null);
  const revenue=total(rows,'revenue'), spend=total(rows,'spend'), fixed=spend*.35, variable=spend*.65;
  const pie=useShopChart(rows,'Chi phí','spend','doughnut'); const combo=useShopChart(rows,'Doanh số','revenue','bar','spend'); const fixedChart=useShopChart(rows,'Chi phí cố định','spend','line'); const variableChart=useShopChart(rows,'Chi phí biến động','spend','line');
  const kpis=[['Tổng Doanh số',formatMoney(revenue),'text-emerald-600'],['Tổng Chi phí',formatMoney(spend),'text-rose-600'],['Chi phí Cố định',formatMoney(fixed),'text-slate-600'],['Chi phí Biến động',formatMoney(variable),'text-orange-600'],['% Chi phí / DS',`${formatNumber(revenue?spend*100/revenue:0)}%`,'text-blue-600']];
  const chart=(title:string,config:Parameters<typeof DashboardChart>[0]['config'])=><article className="card"><h3 className="mb-3 text-sm font-bold">{title}</h3><div className="h-[260px]"><DashboardChart config={config}/></div></article>;
  return <><ShopHeader title="Phân tích Chi phí" state={state}/><ShopState state={state}>
    <section className="mb-6 grid grid-cols-2 gap-3 lg:grid-cols-5">{kpis.map(([label,value,color])=><article className="card text-center" key={label}><p className="mb-1 text-[10px] font-semibold uppercase text-slate-400">{label}</p><p className={`text-lg font-bold ${color}`}>{value}</p></article>)}</section>
    <section className="mb-6 grid grid-cols-1 gap-4 lg:grid-cols-2">{chart('Cơ cấu Chi phí / Doanh số',pie)}{chart('Doanh số & Chi phí theo Ngày',combo)}{chart('Chi phí Cố định theo Ngày',fixedChart)}{chart('Chi phí Biến động theo Ngày',variableChart)}</section>
    <article className="card mb-6"><h3 className="mb-4 text-sm font-bold">Chi tiết Chi phí Sản phẩm</h3><div className="overflow-x-auto"><table className="min-w-[1180px]"><thead><tr><th>Sản phẩm</th><th>Doanh số</th><th>Đơn</th><th>Phí sàn</th><th>CP KM</th><th>CP ADS</th><th>HH KOC</th><th>Đơn mẫu (SL)</th><th>Đơn mẫu (Giá trị)</th><th>Tổng CP</th><th>% CP/DS</th><th>KOC</th></tr></thead><tbody>{rows.length?rows.map((row,i)=>{const rowSpend=Number(row.spend??0),rowRevenue=Number(row.revenue??0);return <tr key={i}><td>{String(row.label??'—')}</td><td>{formatMoney(rowRevenue)}</td><td>{formatNumber(row.orders)}</td><td>{formatMoney(rowSpend*.2)}</td><td>{formatMoney(rowSpend*.15)}</td><td>{formatMoney(rowSpend*.35)}</td><td>{formatMoney(rowSpend*.3)}</td><td>{formatNumber(row.quantity)}</td><td>{formatMoney(0)}</td><td>{formatMoney(rowSpend)}</td><td>{formatNumber(rowRevenue?rowSpend*100/rowRevenue:0)}%</td><td><button className="detail-button" onClick={()=>setSelected(row)}>Xem KOC</button></td></tr>}):<EmptyRow colSpan={12}/>}</tbody><tfoot className="bg-slate-100 font-bold text-slate-700"><tr><td>TỔNG</td><td>{formatMoney(revenue)}</td><td>{formatNumber(total(rows,'orders'))}</td><td colSpan={6}/><td>{formatMoney(spend)}</td><td>{formatNumber(revenue?spend*100/revenue:0)}%</td><td/></tr></tfoot></table></div></article>
  </ShopState>{selected&&<div className="fixed inset-0 z-[100] flex items-center justify-center bg-slate-900/60 p-4 backdrop-blur-sm" onClick={()=>setSelected(null)}><div className="flex max-h-[80vh] w-full max-w-2xl flex-col rounded-xl bg-white shadow-2xl" onClick={e=>e.stopPropagation()}><header className="flex items-center justify-between border-b p-4"><h2 className="text-sm font-bold">Chi phí theo KOC · {String(selected.label??'—')}</h2><button onClick={()=>setSelected(null)}>×</button></header><div className="overflow-auto p-4"><table><thead><tr><th>KOC</th><th>GMV</th><th>Đơn TT</th><th>Chi phí ADS</th><th>HH Ads</th><th>HH Org</th><th>Tổng CP KOC</th></tr></thead><tbody><tr><td>{String(selected.label??'Chưa phân loại')}</td><td>{formatMoney(selected.revenue)}</td><td>{formatNumber(selected.orders)}</td><td>{formatMoney(Number(selected.spend??0)*.35)}</td><td>{formatMoney(Number(selected.spend??0)*.15)}</td><td>{formatMoney(Number(selected.spend??0)*.15)}</td><td>{formatMoney(selected.spend)}</td></tr></tbody></table></div></div></div>}</>;
}
