import { useState } from 'react';
import { DashboardChart } from '../../components/DashboardChart';
import { EmptyRow, formatMoney, formatNumber, ShopHeader, ShopState, total, useShopChart, useShopSection, type ShopMetric, type ShopRow } from './shared';

export function ShopSourceDetails() {
  const state=useShopSection('sources'); const {rows}=state; const [metric,setMetric]=useState<ShopMetric>('revenue'); const [detail,setDetail]=useState<ShopRow|null>(null);
  const pie=useShopChart(rows,'Cơ cấu GMV','revenue','doughnut'); const combo=useShopChart(rows,'GMV','revenue','bar','orders'); const trend=useShopChart(rows,metric,metric,'line');
  const sums={revenue:total(rows,'revenue'),orders:total(rows,'orders'),quantity:total(rows,'quantity'),customers:total(rows,'customers'),impressions:total(rows,'impressions'),clicks:total(rows,'clicks')};
  const kpis=[['Tổng GMV',formatMoney(sums.revenue),'text-emerald-600'],['Đơn hàng',formatNumber(sums.orders),'text-blue-600'],['Số món',formatNumber(sums.quantity),'text-indigo-600'],['Khách hàng',formatNumber(sums.customers),'text-violet-600'],['Hiển thị',formatNumber(sums.impressions),'text-slate-600'],['Lượt nhấp',formatNumber(sums.clicks),'text-sky-600'],['Thêm giỏ',formatNumber(sums.quantity),'text-orange-600'],['CTR',`${formatNumber(sums.impressions?sums.clicks*100/sums.impressions:0)}%`,'text-teal-600']];
  return <><ShopHeader title="Chi tiết Nguồn" state={state}/><ShopState state={state}>
    <section className="mb-6 grid grid-cols-2 gap-3 sm:grid-cols-4 lg:grid-cols-8">{kpis.map(([label,value,color])=><article className="card text-center" key={label}><p className="mb-1 text-[10px] font-semibold uppercase text-slate-400">{label}</p><p className={`text-xl font-bold ${color}`}>{value}</p></article>)}</section>
    <section className="mb-6 grid grid-cols-1 gap-4 lg:grid-cols-2"><article className="card"><h3 className="mb-4 text-sm font-bold">Cơ cấu GMV theo Nguồn</h3><div className="h-[280px]"><DashboardChart config={pie}/></div></article><article className="card"><h3 className="mb-4 text-sm font-bold">GMV, CTR & CTOR theo Nguồn</h3><div className="h-[280px]"><DashboardChart config={combo}/></div></article></section>
    <article className="card mb-6"><h3 className="mb-4 text-sm font-bold">Phễu chuyển đổi theo nguồn</h3><div className="overflow-x-auto"><table className="min-w-[980px]"><thead><tr><th>Nguồn</th><th>Hiển thị</th><th>Lượt nhấp</th><th>CTR</th><th>Thêm giỏ</th><th>Tỷ lệ thêm giỏ</th><th>Đơn hàng</th><th>Tỷ lệ chuyển đổi</th><th>Giỏ → Đơn</th></tr></thead><tbody>{rows.length?rows.map((row,i)=>{const imp=Number(row.impressions??0),clicks=Number(row.clicks??0),cart=Number(row.quantity??0),orders=Number(row.orders??0);return <tr key={i}><td>{String(row.label??'—')}</td><td>{formatNumber(imp)}</td><td>{formatNumber(clicks)}</td><td>{formatNumber(imp?clicks*100/imp:0)}%</td><td>{formatNumber(cart)}</td><td>{formatNumber(clicks?cart*100/clicks:0)}%</td><td>{formatNumber(orders)}</td><td>{formatNumber(clicks?orders*100/clicks:0)}%</td><td>{formatNumber(cart?orders*100/cart:0)}%</td></tr>}):<EmptyRow colSpan={9}/>}</tbody></table></div></article>
    <article className="card mb-6"><h3 className="mb-4 text-sm font-bold">Hiệu quả chi tiết theo Nguồn</h3><div className="overflow-x-auto"><table className="min-w-[1120px]"><thead><tr><th>Nguồn</th><th>GMV</th><th>Đơn</th><th>Số món</th><th>Khách</th><th>AOV</th><th>Hiển thị</th><th>Lượt nhấp</th><th>CTR</th><th>Thêm giỏ</th><th>CTOR</th><th>Chi tiết</th></tr></thead><tbody>{rows.length?rows.map((row,i)=>{const orders=Number(row.orders??0),revenue=Number(row.revenue??0),imp=Number(row.impressions??0),clicks=Number(row.clicks??0),cart=Number(row.quantity??0);return <tr key={i}><td>{String(row.label??'—')}</td><td>{formatMoney(revenue)}</td><td>{formatNumber(orders)}</td><td>{formatNumber(cart)}</td><td>{formatNumber(row.customers)}</td><td>{formatMoney(orders?revenue/orders:0)}</td><td>{formatNumber(imp)}</td><td>{formatNumber(clicks)}</td><td>{formatNumber(imp?clicks*100/imp:0)}%</td><td>{formatNumber(cart)}</td><td>{formatNumber(clicks?cart*100/clicks:0)}%</td><td><button className="detail-button" onClick={()=>setDetail(row)}>Xem</button></td></tr>}):<EmptyRow colSpan={12}/>}</tbody></table></div></article>
    <article className="card mb-6"><div className="mb-4 flex flex-wrap items-center gap-4"><h3 className="text-sm font-bold">Diễn biến theo Ngày</h3><label className="ml-auto text-[11px] text-slate-500">Chỉ số: <select className="ml-2 rounded-lg border border-slate-200 bg-white px-2 py-1 text-xs" value={metric} onChange={e=>setMetric(e.target.value as ShopMetric)}><option value="revenue">GMV</option><option value="orders">Đơn hàng</option><option value="quantity">Số món</option><option value="customers">Khách hàng</option><option value="impressions">Hiển thị</option><option value="clicks">Lượt nhấp</option></select></label></div><div className="h-[280px]"><DashboardChart config={trend}/></div></article>
  </ShopState>{detail&&<div className="legacy-modal" onClick={()=>setDetail(null)}><article onClick={e=>e.stopPropagation()}><header><h2>Chi tiết Nguồn: {String(detail.label??'—')}</h2><button onClick={()=>setDetail(null)}>×</button></header><div className="detail-grid">{Object.entries(detail).map(([key,value])=><div key={key}><span>{key}</span><b>{String(value??'—')}</b></div>)}</div></article></div>}</>;
}
