import { useMemo } from 'react';
import { aggregateSources, type RawProduct, type SourceKey } from './shopMetrics';
import { formatMoney, formatNumber } from './shared';

type ModalProps = { onClose:()=>void };
function ModalFrame({title,onClose,children}:{title:string;children:React.ReactNode}&ModalProps){return <div className="fixed inset-0 z-[100] flex items-center justify-center bg-slate-900/60 p-4 backdrop-blur-sm" onClick={onClose}><article className="flex max-h-[86vh] w-full max-w-6xl flex-col overflow-hidden rounded-xl bg-white shadow-2xl" onClick={event=>event.stopPropagation()}><header className="flex items-center justify-between border-b border-slate-200 px-5 py-4"><h2 className="font-display text-lg font-bold text-slate-900">{title}</h2><button className="text-2xl text-slate-400 hover:text-slate-700" onClick={onClose}>×</button></header><div className="overflow-auto p-5">{children}</div></article></div>}
const pct=(value:number)=>`${formatNumber(value*100)}%`;
function MetricsTable({rows,firstLabel}:{rows:Array<{label:string;gmv:number;sales:number;orders:number;customers:number;impressions:number;clicks:number;atc:number;ctr:number;ctor:number;conversionRate:number}>;firstLabel:string}){return <table className="min-w-[1050px]"><thead><tr><th>{firstLabel}</th><th>GMV Net</th><th>Số món Net</th><th>Đơn Net</th><th>Khách hàng</th><th>Hiển thị</th><th>Lượt nhấp</th><th>CTR</th><th>Thêm giỏ</th><th>CTOR</th><th>Chuyển đổi</th></tr></thead><tbody>{rows.length?rows.map((row,index)=><tr key={`${row.label}-${index}`}><td className="font-semibold text-slate-800">{row.label}</td><td>{formatMoney(row.gmv)}</td><td>{formatNumber(row.sales)}</td><td>{formatNumber(row.orders)}</td><td>{formatNumber(row.customers)}</td><td>{formatNumber(row.impressions)}</td><td>{formatNumber(row.clicks)}</td><td className="text-blue-600">{pct(row.ctr)}</td><td>{formatNumber(row.atc)}</td><td className="text-purple-600">{pct(row.ctor)}</td><td className="text-emerald-600">{pct(row.conversionRate)}</td></tr>):<tr><td colSpan={11} className="empty-cell">Không có dữ liệu chi tiết trong khoảng ngày đã chọn</td></tr>}</tbody></table>}

export function ShopSourceProductsModal({sourceKey,sourceLabel,products,onClose}:{sourceKey:SourceKey;sourceLabel:string;products:RawProduct[]}&ModalProps){const rows=useMemo(()=>{const grouped=new Map<string,RawProduct[]>();products.forEach(product=>{const key=product.productId||product.productName;grouped.set(key,[...(grouped.get(key)??[]),product])});return [...grouped.values()].map(items=>{const metric=aggregateSources(items).find(source=>source.key===sourceKey)!;return {...metric,label:items[0].productName||items[0].productId}}).filter(row=>row.gmv||row.orders||row.sales||row.impressions||row.clicks||row.atc).sort((a,b)=>b.gmv-a.gmv)},[products,sourceKey]);return <ModalFrame title={`Chi tiết Nguồn · ${sourceLabel}`} onClose={onClose}><MetricsTable rows={rows} firstLabel="Sản phẩm"/></ModalFrame>}

export function ShopProductSourcesModal({productId,productLabel,products,onClose}:{productId:string;productLabel:string;products:RawProduct[]}&ModalProps){const rows=useMemo(()=>aggregateSources(products.filter(product=>(product.productId||product.productName)===productId)).filter(row=>row.gmv||row.orders||row.sales||row.impressions||row.clicks||row.atc),[products,productId]);return <ModalFrame title={`Chi tiết Sản phẩm · ${productLabel}`} onClose={onClose}><MetricsTable rows={rows} firstLabel="Nguồn traffic"/></ModalFrame>}
