import { useMemo, useState } from 'react';
import type { ChartConfiguration } from 'chart.js';
import { DashboardChart } from '../../components/DashboardChart';
import { EmptyRow, formatMoney, formatNumber, ShopHeader, ShopState, total, useShopChart, useShopTraffic, type ShopMetric, type ShopRow } from './shared';
import { aggregateSourcesByDate } from './shopMetrics';

export function ShopSourceDetails() {
  const state=useShopTraffic('sources'); const {rows}=state; const visibleRows=rows.filter(row=>row.key!=='shopTab'); const [metric,setMetric]=useState<ShopMetric>('revenue'); const [detail,setDetail]=useState<ShopRow|null>(null);
  const pie=useShopChart(visibleRows,'Cơ cấu GMV','revenue','doughnut'); const trend=useShopChart(rows,metric,metric,'line');
  const daily=useMemo(()=>aggregateSourcesByDate(state.rawProducts),[state.rawProducts]);
  const combo=useMemo<ChartConfiguration>(()=>{const visibleKeys=['sellerLive','sellerVideo','affiliate','card'] as const;const colors={sellerLive:'#ec4899',sellerVideo:'#3b82f6',affiliate:'#8b5cf6',card:'#f59e0b'};const labels=daily.map(day=>{const [year,month,date]=day.date.split('-');return year?`${date}/${month}`:day.date});return {type:'bar',data:{labels,datasets:[...visibleKeys.map(key=>({type:'bar' as const,label:daily[0]?.sources.find(source=>source.key===key)?.label??key,data:daily.map(day=>day.sources.find(source=>source.key===key)?.gmv??0),backgroundColor:colors[key],stack:'gmv',yAxisID:'y'})),{type:'line' as const,label:'CTR (%)',data:daily.map(day=>day.total.ctr*100),borderColor:'#10b981',backgroundColor:'#10b981',yAxisID:'y1',tension:.3,pointRadius:3},{type:'line' as const,label:'CTOR (%)',data:daily.map(day=>day.total.ctor*100),borderColor:'#ef4444',backgroundColor:'#ef4444',borderDash:[4,3],yAxisID:'y1',tension:.3,pointRadius:3}]},options:{responsive:true,maintainAspectRatio:false,interaction:{mode:'index',intersect:false},plugins:{legend:{position:'bottom',labels:{boxWidth:12,font:{size:9}}}},scales:{x:{stacked:true,grid:{display:false}},y:{stacked:true,beginAtZero:true,grid:{color:'#edf0f4'}},y1:{beginAtZero:true,position:'right',grid:{display:false},ticks:{callback:value=>`${value}%`}}}}} as ChartConfiguration;},[daily]);
  const sums={revenue:total(rows,'revenue'),orders:total(rows,'orders'),sales:total(rows,'sales'),customers:total(rows,'customers'),impressions:total(rows,'impressions'),clicks:total(rows,'clicks'),atc:total(rows,'atc')};
  const kpis=[['Tổng GMV',formatMoney(sums.revenue),'text-emerald-600'],['Đơn hàng',formatNumber(sums.orders),'text-blue-600'],['Số món',formatNumber(sums.sales),'text-indigo-600'],['Khách hàng',formatNumber(sums.customers),'text-violet-600'],['Hiển thị',formatNumber(sums.impressions),'text-slate-600'],['Lượt nhấp',formatNumber(sums.clicks),'text-sky-600'],['Thêm giỏ',formatNumber(sums.atc),'text-orange-600'],['CTR',`${formatNumber(sums.impressions?sums.clicks*100/sums.impressions:0)}%`,'text-teal-600']];
  return <><ShopHeader title="Chi tiết Nguồn" state={state}/><ShopState state={state}>
    <section className="mb-6 grid grid-cols-2 gap-3 sm:grid-cols-4 lg:grid-cols-8">{kpis.map(([label,value,color])=><article className="card text-center" key={label}><p className="mb-1 text-[10px] font-semibold uppercase text-slate-400">{label}</p><p className={`text-xl font-bold ${color}`}>{value}</p></article>)}</section>
    <section className="mb-6 grid grid-cols-1 gap-4 lg:grid-cols-2"><article className="card"><h3 className="mb-4 text-sm font-bold">Cơ cấu GMV theo Nguồn</h3><div className="h-[280px]"><DashboardChart config={pie}/></div></article><article className="card"><h3 className="mb-4 text-sm font-bold">GMV, CTR & CTOR theo Nguồn</h3><div className="h-[280px]"><DashboardChart config={combo}/></div></article></section>
    <article className="card mb-6"><h3 className="mb-4 text-sm font-bold">Phễu chuyển đổi theo nguồn</h3><div className="overflow-x-auto"><table className="min-w-[980px]"><thead><tr><th>Nguồn</th><th>Hiển thị</th><th>Lượt nhấp</th><th>CTR</th><th>Thêm giỏ</th><th>Tỷ lệ thêm giỏ</th><th>Đơn hàng</th><th>Tỷ lệ chuyển đổi</th><th>Giỏ → Đơn</th></tr></thead><tbody>{rows.length?rows.map((row,i)=>{const imp=Number(row.impressions??0),clicks=Number(row.clicks??0),cart=Number(row.atc??0),orders=Number(row.orders??0);return <tr key={i}><td>{String(row.label??'—')}</td><td>{formatNumber(imp)}</td><td>{formatNumber(clicks)}</td><td>{formatNumber(Number(row.ctr??0)*100)}%</td><td>{formatNumber(cart)}</td><td>{formatNumber(Number(row.addToCartRate??0)*100)}%</td><td>{formatNumber(orders)}</td><td>{formatNumber(Number(row.conversionRate??0)*100)}%</td><td>{formatNumber(Number(row.cartToOrderRate??0)*100)}%</td></tr>}):<EmptyRow colSpan={9}/>}</tbody></table></div></article>
    <article className="card mb-6"><h3 className="mb-4 text-sm font-bold">Hiệu quả chi tiết theo Nguồn</h3><div className="overflow-x-auto"><table className="min-w-[1120px]"><thead><tr><th>Nguồn</th><th>GMV</th><th>Đơn</th><th>Số món</th><th>Khách</th><th>AOV</th><th>Hiển thị</th><th>Lượt nhấp</th><th>CTR</th><th>Thêm giỏ</th><th>CTOR</th><th>Chi tiết</th></tr></thead><tbody>{rows.length?rows.map((row,i)=>{return <tr key={i}><td>{String(row.label??'—')}</td><td>{formatMoney(row.revenue)}</td><td>{formatNumber(row.orders)}</td><td>{formatNumber(row.sales)}</td><td>{formatNumber(row.customers)}</td><td>{formatMoney(row.aov)}</td><td>{formatNumber(row.impressions)}</td><td>{formatNumber(row.clicks)}</td><td>{formatNumber(Number(row.ctr??0)*100)}%</td><td>{formatNumber(row.atc)}</td><td>{formatNumber(Number(row.ctor??0)*100)}%</td><td><button className="detail-button" onClick={()=>setDetail(row)}>Xem</button></td></tr>}):<EmptyRow colSpan={12}/>}</tbody></table></div></article>
    <article className="card mb-6"><div className="mb-4 flex flex-wrap items-center gap-4"><h3 className="text-sm font-bold">Diễn biến theo Ngày</h3><label className="ml-auto text-[11px] text-slate-500">Chỉ số: <select className="ml-2 rounded-lg border border-slate-200 bg-white px-2 py-1 text-xs" value={metric} onChange={e=>setMetric(e.target.value as ShopMetric)}><option value="revenue">GMV</option><option value="orders">Đơn hàng</option><option value="quantity">Số món</option><option value="customers">Khách hàng</option><option value="impressions">Hiển thị</option><option value="clicks">Lượt nhấp</option></select></label></div><div className="h-[280px]"><DashboardChart config={trend}/></div></article>
  </ShopState>{detail&&<div className="legacy-modal" onClick={()=>setDetail(null)}><article onClick={e=>e.stopPropagation()}><header><h2>Chi tiết Nguồn: {String(detail.label??'—')}</h2><button onClick={()=>setDetail(null)}>×</button></header><div className="detail-grid">{Object.entries(detail).map(([key,value])=><div key={key}><span>{key}</span><b>{String(value??'—')}</b></div>)}</div></article></div>}</>;
}
